{% set name = "bokeh-fastapi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh_fastapi-{{ version }}.tar.gz
  sha256: f01f035f9c275d416a83d9c7f1aa06d9c76b47e565b0d8795d1902f01977d57f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - fastapi >=0.68.0
    - starlette
    - bokeh >=2.3.3

test:
  imports:
    - bokeh_fastapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bokeh/bokeh-fastapi
  summary: Compatibility layer between Bokeh and FastAPI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmeier
    - philippjfr
