{% set name = "bokeh-fastapi" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh_fastapi-{{ version }}.tar.gz
  sha256: 45504b212d6af5bc6edf56e7b267d184f2e4c11ff457a78f244a4d5e09ba1a51

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python >=3.10
        - setuptools >=64
        - setuptools-scm >=8
        - pip
      run:
        - python >=3.10
        - bokeh >=2.3.3
        - fastapi >=0.68.0
        - starlette
        - websockets>=10.4
    test:
      imports:
        - bokeh_fastapi
      commands:
        - pip check
      requires:
        - pip

  # So we can run conda install bokeh_fastapi
  - name: bokeh_fastapi
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - bokeh_fastapi


about:
  home: https://github.com/bokeh/bokeh-fastapi
  summary: Compatibility layer between Bokeh and FastAPI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmeier
    - philippjfr
