{% set name = "bokeh-fastapi" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh_fastapi-{{ version }}.tar.gz
  sha256: 8375d3d9971c8fdedbd8aa13bdc37878e04c8cb653a51919c2dad069a94f7d91

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python >=3.10
        - setuptools >=64
        - setuptools-scm >=8
        - pip
      run:
        - python >=3.10
        - fastapi >=0.68.0
        - starlette
        - bokeh >=2.3.3
    test:
      imports:
      - bokeh_fastapi
      commands:
      - pip check
      requires:
      - pip

  # So we can run conda install bokeh_fastapi
  - name: bokeh_fastapi
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - bokeh_fastapi


about:
  home: https://github.com/bokeh/bokeh-fastapi
  summary: Compatibility layer between Bokeh and FastAPI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmeier
    - philippjfr
