{% set name = "bokeh-fastapi" %}
{% set version = "0.1.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh_fastapi-{{ version }}.tar.gz
  sha256: d093a694b4732bf2095f1edd09304cd5d7f91a76fab6ca3d98cda265f40676e6
  patches:
    - 000-bokeh-390.patch

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=64
        - setuptools-scm >=8
        - pip
      run:
        - python >={{ python_min }}
        - bokeh >=2.3.3
        - fastapi >=0.68.0
        - starlette
        - websockets >=10.4
    test:
      imports:
        - bokeh_fastapi
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  # So we can run conda install bokeh_fastapi
  - name: bokeh_fastapi
    build:
      noarch: python
    requirements:
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - bokeh_fastapi
      requires:
        - python {{ python_min }}
        - pip


about:
  home: https://github.com/bokeh/bokeh-fastapi
  summary: Compatibility layer between Bokeh and FastAPI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmeier
    - philippjfr
    - hoxbro
